apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-bucket-config
  namespace: seimei-handan
data:
  # バケット設定
  BUCKET_NAME: "seimei-handan-bucket"
  LOCATION: "asia-northeast1"
  STORAGE_CLASS: "STANDARD"
  VERSIONING_ENABLED: "true"
  LIFECYCLE_ENABLED: "true"
  
  # アクセス制御設定
  UNIFORM_BUCKET_LEVEL_ACCESS: "true"
  PUBLIC_ACCESS_PREVENTION: "enforced"
  
  # CORS設定
  CORS_ORIGIN: "*"
  CORS_METHOD: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_HEADER: "Content-Type,Authorization,X-Requested-With"
  CORS_MAX_AGE: "3600"
  
  # ライフサイクル設定
  LIFECYCLE_DELETE_DAYS: "365"
  LIFECYCLE_ARCHIVE_DAYS: "30"
  LIFECYCLE_ARCHIVE_CLASS: "NEARLINE"

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-service-account
  namespace: seimei-handan
type: Opaque
data:
  # 実際のサービスアカウントキーをBase64エンコードして設定
  # 例: echo -n '{"type":"service_account",...}' | base64
  key.json: ""

---
# Cloud StorageはCloud Functionsからのみアクセスするため、
# Kubernetes内での直接管理は不要
# バケットの作成と設定はTerraformで行う
